meta:
  appTitle: "OnlineZap Backend"
  toolchain: docker

services:
  backendlonlinezap:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    containerPort: 8000
    persistence:
      - mount: /app/Data
        name: backend-data
    args: []

postgresql:
  - name: onlinezap-db
    version: "16"
    disks:
      etalon:
        size: 1024
