meta:
  appTitle: "OnlineZap Frontend"
  toolchain: docker

services:
  frontendlonlinezap:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    containerPort: 80
    persistence:
      - mount: /data
        name: frontend-data
    args: []
